[build]
  # Specify the directory containing your website files
  publish = "reports/08_final_delivery"
  
  # No build command needed since this is a static HTML site
  # command = ""

[build.environment]
  # Set environment variables if needed
  NODE_VERSION = "18"

# Redirects for clean URLs (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self';"

# Specific headers for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Specific headers for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Specific headers for images
[[headers]]
  for = "*.jpg,*.jpeg,*.png,*.gif,*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 